# -*- coding: utf-8 -*-
"""Ai story Generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o8BfGZe-eKvwyUSIPN4VbsTltAKCBLWe
"""

import gradio as gr
import fitz  # PyMuPDF
import re
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras import layers, Model, Input
import tensorflow.keras.backend as K

# Text extraction function
def extract_text_from_pdf(path):
    doc = fitz.open(path)
    text = "/content/Bound_by_Alpha_and_Omega.pdf"
    for page in doc:
        text += page.get_text()
    return text

# Function to process the text and tokenize it
def process_text(raw_text):
    cleaned_text = re.sub(r'\s+', ' ', raw_text.strip())
    sentences = re.split(r'(?<=[.!?])\s+', cleaned_text)
    sentences = [s.strip() for s in sentences if len(s.split()) > 3]  # Remove very short sentences

    tokenizer = Tokenizer(oov_token="<OOV>")
    tokenizer.fit_on_texts(sentences)

    sequences = tokenizer.texts_to_sequences(sentences)
    padded = pad_sequences(sequences, padding='post')
    vocab_size = len(tokenizer.word_index) + 1
    input_dim = padded.shape[1]

    return padded, tokenizer, vocab_size, input_dim

# Build the VAE model
def build_vae_model(vocab_size, input_dim):
    latent_dim = 32
    encoder_inputs = Input(shape=(input_dim,))
    x = layers.Embedding(vocab_size, 64)(encoder_inputs)
    x = layers.LSTM(64)(x)
    z_mean = layers.Dense(latent_dim)(x)
    z_log_var = layers.Dense(latent_dim)(x)

    def sampling(args):
        z_mean, z_log_var = args
        epsilon = tf.random.normal(shape=(tf.shape(z_mean)[0], latent_dim))
        return z_mean + tf.exp(0.5 * z_log_var) * epsilon

    z = layers.Lambda(sampling)([z_mean, z_log_var])

    decoder_inputs = layers.RepeatVector(input_dim)(z)
    x = layers.LSTM(64, return_sequences=True)(decoder_inputs)
    decoder_outputs = layers.TimeDistributed(layers.Dense(vocab_size, activation="softmax"))(x)

    vae = Model(encoder_inputs, decoder_outputs)

    def vae_loss(encoder_inputs, decoder_outputs, z_mean, z_log_var):
        reconstruction_loss = K.sum(
            K.sparse_categorical_crossentropy(encoder_inputs, decoder_outputs), axis=1
        )
        kl_loss = -0.5 * K.sum(1 + z_log_var - K.square(z_mean) - K.exp(z_log_var), axis=1)
        return K.mean(reconstruction_loss + kl_loss)

    class VAELossLayer(layers.Layer):
        def call(self, inputs):
            encoder_inputs, decoder_outputs, z_mean, z_log_var = inputs
            loss = vae_loss(encoder_inputs, decoder_outputs, z_mean, z_log_var)
            self.add_loss(loss)
            return decoder_outputs

    loss_layer = VAELossLayer()([encoder_inputs, decoder_outputs, z_mean, z_log_var])
    vae = Model(encoder_inputs, loss_layer)
    vae.compile(optimizer="adam")

    return vae

# Gradio function to generate text from a PDF file
def generate_text_from_pdf(pdf_file):
    raw_text = extract_text_from_pdf(pdf_file.name)
    padded, tokenizer, vocab_size, input_dim = process_text(raw_text)

    vae = build_vae_model(vocab_size, input_dim)
    vae.fit(padded, padded, epochs=50, batch_size=16)

    latent_inputs = Input(shape=(32,))
    x = layers.RepeatVector(input_dim)(latent_inputs)
    x = layers.LSTM(64, return_sequences=True)(x)
    decoder_outputs = layers.TimeDistributed(layers.Dense(vocab_size, activation="softmax"))(x)
    decoder = Model(latent_inputs, decoder_outputs)

    # Generate Text
    z_sample = np.random.normal(size=(1, 32))
    generated = decoder.predict(z_sample)
    generated_seq = [np.random.choice(vocab_size, p=token_probs / np.sum(token_probs))
                     for token_probs in generated[0]]
    generated_text = tokenizer.sequences_to_texts([generated_seq])[0]

    return generated_text

# Gradio Interface
iface = gr.Interface(
    fn=generate_text_from_pdf,
    inputs=gr.inputs.File(label="Upload PDF"),
    outputs=gr.outputs.Textbox(label="Generated Text"),
    live=True
)

# Launch the Gradio app
iface.launch()